import { db } from '@/lib/db';
import type { YieldReference, PlantCategory } from '@/types/plant';

/**
 * Seed yield reference data into IndexedDB on first load.
 * This is the single source of truth for expected yields —
 * components read from the DB, never from hardcoded values.
 */
const YIELD_REFERENCE_DATA: Omit<YieldReference, 'id'>[] = [
  // ── Vegetables ──────────────────────────────────────────────────────────
  {
    plantName: 'Tomato',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 4500,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 70,
    daysToLastHarvest: 150,
    harvestsPerSeason: 15,
    yieldRatingThresholds: { veryLow: 500, low: 1500, moderate: 3000, high: 5000, veryHigh: 8000 },
    tips: 'Prune suckers for larger fruit. In Thai heat, cherry varieties yield more reliably than beefsteak.',
  },
  {
    plantName: 'Chili Pepper',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 800,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 80,
    daysToLastHarvest: 200,
    harvestsPerSeason: 20,
    yieldRatingThresholds: { veryLow: 100, low: 300, moderate: 600, high: 1000, veryHigh: 1500 },
    tips: 'Thai bird chili (พริกขี้หนู) yields heavily. Pick frequently to encourage more fruiting.',
  },
  {
    plantName: 'Cucumber',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 3000,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 50,
    daysToLastHarvest: 90,
    harvestsPerSeason: 10,
    yieldRatingThresholds: { veryLow: 300, low: 1000, moderate: 2000, high: 3500, veryHigh: 5000 },
    tips: 'Harvest young for best flavor. Trellis growing improves air circulation and yield in humid Thai climate.',
  },
  {
    plantName: 'Eggplant',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 2500,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 70,
    daysToLastHarvest: 150,
    harvestsPerSeason: 12,
    yieldRatingThresholds: { veryLow: 300, low: 800, moderate: 1800, high: 3000, veryHigh: 4500 },
    tips: 'Thai pea eggplant (มะเขือพวง) yields hundreds of small fruits per plant.',
  },
  {
    plantName: 'Lettuce',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 350,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 30,
    daysToLastHarvest: 60,
    harvestsPerSeason: 3,
    yieldRatingThresholds: { veryLow: 50, low: 150, moderate: 300, high: 450, veryHigh: 600 },
    tips: 'Harvest outer leaves for cut-and-come-again. Shade cloth essential in Thai climate.',
  },
  {
    plantName: 'Kale',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 500,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 55,
    daysToLastHarvest: 120,
    harvestsPerSeason: 8,
    yieldRatingThresholds: { veryLow: 80, low: 200, moderate: 400, high: 600, veryHigh: 900 },
    tips: 'Chinese kale (คะน้า) is more heat-tolerant than Western varieties.',
  },
  {
    plantName: 'Water Spinach',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 1200,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 25,
    daysToLastHarvest: 90,
    harvestsPerSeason: 6,
    yieldRatingThresholds: { veryLow: 200, low: 500, moderate: 900, high: 1500, veryHigh: 2000 },
    tips: 'Morning glory (ผักบุ้ง) regrows from cut stems. Keep soil wet for maximum yield.',
  },
  {
    plantName: 'Long Bean',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 1500,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 55,
    daysToLastHarvest: 120,
    harvestsPerSeason: 12,
    yieldRatingThresholds: { veryLow: 200, low: 600, moderate: 1200, high: 1800, veryHigh: 2500 },
    tips: 'Pick pods when 30-40cm. Trellising dramatically increases yield and ease of harvest.',
  },
  {
    plantName: 'Okra',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 1000,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 55,
    daysToLastHarvest: 130,
    harvestsPerSeason: 25,
    yieldRatingThresholds: { veryLow: 150, low: 400, moderate: 800, high: 1200, veryHigh: 1800 },
    tips: 'Harvest pods at 7-8cm for tenderness. Produces almost daily in Thai heat.',
  },
  {
    plantName: 'Bitter Melon',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 2000,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 55,
    daysToLastHarvest: 120,
    harvestsPerSeason: 8,
    yieldRatingThresholds: { veryLow: 300, low: 800, moderate: 1500, high: 2500, veryHigh: 3500 },
    tips: 'Hand pollinate for reliable fruiting. Harvest while still green and firm.',
  },
  {
    plantName: 'Sweet Potato',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 1500,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 100,
    daysToLastHarvest: 150,
    harvestsPerSeason: 1,
    yieldRatingThresholds: { veryLow: 200, low: 500, moderate: 1200, high: 2000, veryHigh: 3000 },
    tips: 'Thai purple sweet potato yields well in sandy loam. Leaves are also edible.',
  },
  {
    plantName: 'Corn',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 350,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 70,
    daysToLastHarvest: 90,
    harvestsPerSeason: 1,
    yieldRatingThresholds: { veryLow: 50, low: 150, moderate: 280, high: 400, veryHigh: 550 },
    tips: 'Plant in blocks (not rows) for wind pollination. Thai waxy corn (ข้าวโพดข้าวเหนียว) is popular.',
  },
  {
    plantName: 'Pumpkin',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 5000,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 90,
    daysToLastHarvest: 130,
    harvestsPerSeason: 3,
    yieldRatingThresholds: { veryLow: 500, low: 1500, moderate: 3500, high: 6000, veryHigh: 10000 },
    tips: 'Thai pumpkin (ฟักทอง) is smaller and denser than Western varieties. Train on trellis to save space.',
  },
  {
    plantName: 'Radish',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 80,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 25,
    daysToLastHarvest: 40,
    harvestsPerSeason: 1,
    yieldRatingThresholds: { veryLow: 10, low: 30, moderate: 60, high: 100, veryHigh: 150 },
    tips: 'Very fast crop. Succession sow every 2 weeks for continuous harvest.',
  },
  {
    plantName: 'Carrot',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 120,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 60,
    daysToLastHarvest: 80,
    harvestsPerSeason: 1,
    yieldRatingThresholds: { veryLow: 20, low: 50, moderate: 100, high: 150, veryHigh: 200 },
    tips: 'Deep loose soil is essential. Tropical short varieties do better in Thai soil.',
  },
  {
    plantName: 'Chinese Cabbage',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 800,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 50,
    daysToLastHarvest: 70,
    harvestsPerSeason: 1,
    yieldRatingThresholds: { veryLow: 100, low: 300, moderate: 600, high: 1000, veryHigh: 1500 },
    tips: 'Cool season only in Thailand. Start in October for best results.',
  },
  {
    plantName: 'Spinach',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 250,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 35,
    daysToLastHarvest: 60,
    harvestsPerSeason: 3,
    yieldRatingThresholds: { veryLow: 30, low: 100, moderate: 200, high: 300, veryHigh: 450 },
    tips: 'Malabar spinach is the heat-tolerant alternative for year-round growing.',
  },
  {
    plantName: 'Malabar Spinach',
    category: 'vegetable',
    expectedYieldGramsPerPlant: 1000,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 40,
    daysToLastHarvest: 120,
    harvestsPerSeason: 8,
    yieldRatingThresholds: { veryLow: 100, low: 400, moderate: 800, high: 1200, veryHigh: 1800 },
    tips: 'Climbing vine that thrives in Thai heat. Very productive once established.',
  },

  // ── Herbs ───────────────────────────────────────────────────────────────
  {
    plantName: 'Thai Basil',
    category: 'herb',
    expectedYieldGramsPerPlant: 400,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 30,
    daysToLastHarvest: 120,
    harvestsPerSeason: 8,
    yieldRatingThresholds: { veryLow: 50, low: 150, moderate: 300, high: 500, veryHigh: 700 },
    tips: 'Pinch flowers to encourage bushy growth and continuous leaf production.',
  },
  {
    plantName: 'Holy Basil',
    category: 'herb',
    expectedYieldGramsPerPlant: 350,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 35,
    daysToLastHarvest: 120,
    harvestsPerSeason: 7,
    yieldRatingThresholds: { veryLow: 40, low: 120, moderate: 280, high: 450, veryHigh: 600 },
    tips: 'Krapao (กะเพรา). Essential for pad krapao. Harvest before flowering for best flavor.',
  },
  {
    plantName: 'Cilantro',
    category: 'herb',
    expectedYieldGramsPerPlant: 80,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 25,
    daysToLastHarvest: 50,
    harvestsPerSeason: 2,
    yieldRatingThresholds: { veryLow: 10, low: 30, moderate: 60, high: 100, veryHigh: 150 },
    tips: 'Bolts very fast in Thai heat. Sow every 2 weeks. Cool season only for reliable yield.',
  },
  {
    plantName: 'Lemongrass',
    category: 'herb',
    expectedYieldGramsPerPlant: 800,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 90,
    daysToLastHarvest: 365,
    harvestsPerSeason: 4,
    yieldRatingThresholds: { veryLow: 100, low: 300, moderate: 600, high: 1000, veryHigh: 1500 },
    tips: 'Harvest outer stalks. Each clump produces many divisions. Virtually indestructible in Thailand.',
  },
  {
    plantName: 'Galangal',
    category: 'herb',
    expectedYieldGramsPerPlant: 600,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 240,
    daysToLastHarvest: 365,
    harvestsPerSeason: 2,
    yieldRatingThresholds: { veryLow: 80, low: 200, moderate: 450, high: 700, veryHigh: 1000 },
    tips: 'Takes 8-10 months to mature. Harvest when tops start to yellow.',
  },
  {
    plantName: 'Turmeric',
    category: 'herb',
    expectedYieldGramsPerPlant: 500,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 240,
    daysToLastHarvest: 300,
    harvestsPerSeason: 1,
    yieldRatingThresholds: { veryLow: 50, low: 180, moderate: 400, high: 600, veryHigh: 900 },
    tips: 'Harvest when leaves turn yellow. Each rhizome multiplies 5-10x.',
  },
  {
    plantName: 'Ginger',
    category: 'herb',
    expectedYieldGramsPerPlant: 500,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 180,
    daysToLastHarvest: 300,
    harvestsPerSeason: 1,
    yieldRatingThresholds: { veryLow: 60, low: 200, moderate: 400, high: 600, veryHigh: 850 },
    tips: 'Partial shade preferred. Young ginger can be harvested earlier (4 months) for milder flavor.',
  },
  {
    plantName: 'Mint',
    category: 'herb',
    expectedYieldGramsPerPlant: 300,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 20,
    daysToLastHarvest: 90,
    harvestsPerSeason: 6,
    yieldRatingThresholds: { veryLow: 30, low: 100, moderate: 250, high: 400, veryHigh: 550 },
    tips: 'Extremely invasive — always grow in containers. Cut back regularly for bushier growth.',
  },
  {
    plantName: 'Pandan',
    category: 'herb',
    expectedYieldGramsPerPlant: 600,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 60,
    daysToLastHarvest: 365,
    harvestsPerSeason: 12,
    yieldRatingThresholds: { veryLow: 80, low: 200, moderate: 450, high: 700, veryHigh: 1000 },
    tips: 'Harvest lower leaves. Plant produces year-round once established.',
  },

  // ── Fruits ──────────────────────────────────────────────────────────────
  {
    plantName: 'Papaya',
    category: 'fruit',
    expectedYieldGramsPerPlant: 25000,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 240,
    daysToLastHarvest: 365,
    harvestsPerSeason: 15,
    yieldRatingThresholds: { veryLow: 3000, low: 10000, moderate: 20000, high: 30000, veryHigh: 50000 },
    tips: 'Green papaya for som tum, ripe for eating. Each tree produces 30-50 kg/year in Thailand.',
  },
  {
    plantName: 'Banana',
    category: 'fruit',
    expectedYieldGramsPerPlant: 15000,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 270,
    daysToLastHarvest: 365,
    harvestsPerSeason: 1,
    yieldRatingThresholds: { veryLow: 2000, low: 7000, moderate: 12000, high: 18000, veryHigh: 25000 },
    tips: 'Each plant fruits once then produces suckers. Namwa variety is most common in Thailand.',
  },
  {
    plantName: 'Dragon Fruit',
    category: 'fruit',
    expectedYieldGramsPerPlant: 8000,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 365,
    daysToLastHarvest: 545,
    harvestsPerSeason: 5,
    yieldRatingThresholds: { veryLow: 1000, low: 3000, moderate: 6000, high: 10000, veryHigh: 15000 },
    tips: 'Hand pollinate at night for better fruit set. Full sun essential.',
  },
  {
    plantName: 'Passion Fruit',
    category: 'fruit',
    expectedYieldGramsPerPlant: 5000,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 180,
    daysToLastHarvest: 365,
    harvestsPerSeason: 20,
    yieldRatingThresholds: { veryLow: 500, low: 2000, moderate: 4000, high: 6000, veryHigh: 9000 },
    tips: 'Self-fertile varieties available. Let fruit drop naturally for best sweetness.',
  },
  {
    plantName: 'Guava',
    category: 'fruit',
    expectedYieldGramsPerPlant: 20000,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 365,
    daysToLastHarvest: 545,
    harvestsPerSeason: 30,
    yieldRatingThresholds: { veryLow: 2000, low: 8000, moderate: 15000, high: 25000, veryHigh: 35000 },
    tips: 'Thai guava (ฝรั่ง) is very productive. Bag fruit to protect from fruit flies.',
  },
  {
    plantName: 'Lime',
    category: 'fruit',
    expectedYieldGramsPerPlant: 10000,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 365,
    daysToLastHarvest: 730,
    harvestsPerSeason: 50,
    yieldRatingThresholds: { veryLow: 1000, low: 4000, moderate: 8000, high: 12000, veryHigh: 18000 },
    tips: 'Kaffir lime for leaves, regular lime for juice. Year-round production in Thailand.',
  },

  // ── Flowers ─────────────────────────────────────────────────────────────
  {
    plantName: 'Marigold',
    category: 'flower',
    expectedYieldGramsPerPlant: 200,
    yieldUnit: 'flowers/plant',
    daysToFirstHarvest: 50,
    daysToLastHarvest: 120,
    harvestsPerSeason: 20,
    yieldRatingThresholds: { veryLow: 20, low: 80, moderate: 150, high: 250, veryHigh: 400 },
    tips: 'Deadhead regularly for continuous blooming. Great companion plant for pest control.',
  },
  {
    plantName: 'Sunflower',
    category: 'flower',
    expectedYieldGramsPerPlant: 100,
    yieldUnit: 'g seeds/plant',
    daysToFirstHarvest: 70,
    daysToLastHarvest: 90,
    harvestsPerSeason: 1,
    yieldRatingThresholds: { veryLow: 10, low: 40, moderate: 80, high: 120, veryHigh: 180 },
    tips: 'Grow in cool season for best results. Dwarf varieties work well in Thai gardens.',
  },

  // ── Medicinal ───────────────────────────────────────────────────────────
  {
    plantName: 'Aloe Vera',
    category: 'medicinal',
    expectedYieldGramsPerPlant: 1000,
    yieldUnit: 'g/plant',
    daysToFirstHarvest: 180,
    daysToLastHarvest: 365,
    harvestsPerSeason: 4,
    yieldRatingThresholds: { veryLow: 100, low: 400, moderate: 800, high: 1200, veryHigh: 1800 },
    tips: 'Harvest outer leaves only. Allow at least 8 leaves to remain for plant health.',
  },
  {
    plantName: 'Moringa',
    category: 'medicinal',
    expectedYieldGramsPerPlant: 2000,
    yieldUnit: 'g leaves/plant',
    daysToFirstHarvest: 60,
    daysToLastHarvest: 365,
    harvestsPerSeason: 10,
    yieldRatingThresholds: { veryLow: 200, low: 800, moderate: 1500, high: 2500, veryHigh: 4000 },
    tips: 'Extremely fast growing in Thai climate. Prune hard to keep accessible height.',
  },
  {
    plantName: 'Butterfly Pea',
    category: 'medicinal',
    expectedYieldGramsPerPlant: 300,
    yieldUnit: 'g flowers/plant',
    daysToFirstHarvest: 60,
    daysToLastHarvest: 200,
    harvestsPerSeason: 30,
    yieldRatingThresholds: { veryLow: 30, low: 100, moderate: 250, high: 400, veryHigh: 600 },
    tips: 'อัญชัน flowers daily. Pick in the morning for best color. Dry for tea.',
  },
];

/**
 * Seeds the yieldReferences table if it's empty.
 * Called once on app startup.
 */
export async function seedYieldReferences(): Promise<void> {
  const count = await db.yieldReferences.count();
  if (count > 0) return; // already seeded
  await db.yieldReferences.bulkAdd(YIELD_REFERENCE_DATA as any[]);
}
